services:
  bck:
    build: .
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
      - PORT=6000
    restart: unless-stopped
    volumes:
      - bck-data:/app/db.json

volumes:
  bck-data:
