services:
  bck:
    build: .
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - PORT=9000
    restart: unless-stopped
    volumes:
      - bck-data:/app/db.json

volumes:
  bck-data:
