import { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';

const LangContext = createContext(null);

const translations = {
  en: {
    // common
    appName: "BCK Backup System",
    allSystemsOperational: "All systems operational",
    healthy: "Stable",
    degraded: "Degraded",
    idle: "Idle",
    refresh: "Refresh",
    download: "Download",
    viewAll: "View All",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    create: "Create",
    add: "Add",
    name: "Name",
    status: "Status",
    createdAt: "Created At",
    updatedAt: "Updated At",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    info: "Info",
    warning: "Warning",
    search: "Search",
    type: "Type",
    active: "Active",
    inactive: "Inactive",
    yes: "Yes",
    no: "No",
    confirm: "Confirm",
    description: "Description",
    role: "Role",
    email: "Email",
    username: "Username",
    password: "Password",
    // sidebar & navbar
    dashboard: "Dashboard",
    backups: "Backups",
    allBackups: "All Backups",
    databases: "Databases",
    vms: "VMs",
    hosts: "Hosts",
    cloud: "Cloud",
    restore: "Restore",
    policies: "Policies",
    history: "Job History",
    logs: "Activity Log",
    settings: "Settings",
    users: "Users",
    roles: "Roles",
    logout: "Logout",
    // login
    loginTitle: "Sign In",
    loginSubtitle: "BCK Backup Management Console",
    loginButton: "Sign In",
    loginError: "Invalid credentials or account disabled",
    defaultCredentials: "Default Credentials",
    // dashboard
    sysOverview: "System Overview",
    sources: "Sources",
    last24h: "Last 24 Hours",
    performance: "Performance",
    storage: "Storage",
    dailyBackupSize: "Daily Backup Size",
    recentActivity: "Recent Activity",
    backupTimeline: "Backup Timeline",
    recentBackups: "Recent Backups",
    quickActions: "Quick Actions",
    activeSchedules: "Active Schedules",
    totalJobs: "Total Jobs",
    completed: "Completed",
    failed: "Failed",
    running: "Running",
    activeNow: "Active / Pending",
    avgSpeed: "MB/s avg",
    expiringSoon: "expiring >{days}d",
    used: "used",
    ofTotal: "of {total} GB total",
    noDataYet: "No data yet",
    noRecentActivity: "No recent activity",
    noBackupsYet: "No backups yet",
    noActiveSchedules: "No active schedules. Create one to automate backups.",
    createFirstBackup: "Create your first backup",
    newBackupBtn: "New Backup",
    manageSchedulesBtn: "Manage Schedules",
    exportDashboardBtn: "Export Dashboard",
    retentionInfo: "Retention: {days} days · {total} backups stored · {expiring} expiring soon",
    lastUpdated: "Last updated",
    // backups CRUD
    addBackup: "Add Backup Job",
    editBackup: "Edit Backup Job",
    sourcePath: "Source Path / Target",
    destPath: "Destination Path",
    backupType: "Backup Type",
    runNow: "Run Now",
    noBackupsConfigured: "No backups configured yet",
    deleteConfirmTitle: "Delete Backup Job?",
    deleteConfirmDesc: "Are you sure you want to delete this backup job? This action cannot be undone.",
    // db connections
    dbConnections: "Database Connections",
    addConnection: "Add Connection",
    editConnection: "Edit Connection",
    testConnection: "Test Connection",
    port: "Port",
    databaseName: "Database Name",
    databasesFound: "Databases found",
    connectionSuccess: "Database connection successful",
    connectionFailed: "Database connection failed",
    // vm backups
    vmName: "VM Name",
    datastore: "Datastore",
    host: "Host",
    // cloud credentials
    cloudCredentials: "Cloud Credentials",
    addCredentials: "Add Credentials",
    editCredentials: "Edit Credentials",
    provider: "Provider",
    accessKeyId: "Access Key ID",
    secretAccessKey: "Secret Access Key",
    region: "Region",
    bucket: "Bucket",
    endpoint: "Endpoint (optional)",
    storageAccount: "Storage Account",
    container: "Container",
    // restore
    restoreTitle: "System Restore",
    restoreSubtitle: "Restore system, databases, or VMs from backup points",
    restorePoint: "Select Backup Point",
    targetConnection: "Target Connection",
    targetPath: "Target Path",
    restoreBtn: "Initiate Restore",
    restoreSuccess: "Restore completed successfully",
    restoreFailed: "Restore failed",
    // policies
    retentionPolicies: "Retention Policies",
    retentionDays: "Retention Days",
    retentionCopies: "Max Backup Copies",
    smtpConfig: "SMTP Configuration",
    smtpHost: "SMTP Host",
    smtpPort: "SMTP Port",
    encryption: "Encryption",
    // schedules
    schedules: "Schedules",
    scheduleList: "Backup Schedules",
    cronExpression: "Cron Expression",
    cronHelper: "Standard cron syntax (* * * * *)",
    everyHour: "Every hour",
    dailyAtMidnight: "Daily at midnight",
    weeklySunday: "Weekly (Sunday)",
    monthlyFirst: "Monthly (1st)",
    custom: "Custom",
    runsEveryHour: "Runs every hour",
    runsDailyAtMidnight: "Runs daily at midnight",
    runsWeeklyOnSunday: "Runs weekly on Sunday",
    runsMonthlyOn1st: "Runs monthly on 1st",
    customSchedule: "Custom schedule",
    nextRun: "Next Run",
    // users
    userList: "User Management",
    addUser: "Add User",
    editUser: "Edit User",
    // roles
    roleList: "Role Management",
    addRole: "Add Role",
    editRole: "Edit Role",
    permissions: "Permissions",
    // policies
    policiesTitle: "Backup Policies",
    policiesSubtitle: "Pre-configured backup policies with retention rules and schedules",
    newPolicy: "New Policy",
    policyName: "Policy Name",
    policy: "Policy",
    retention: "Retention",
    schedule: "Schedule",
    targets: "Targets",
    enabledCol: "Enabled",
    apply: "Apply",
    policyApplied: "Policy \"{name}\" applied to matching backup jobs",
    editPolicy: "Edit Policy",
    newPolicyTitle: "New Backup Policy",
    minCopiesToKeep: "Min copies to keep",
    cronSchedule: "Cron Schedule",
    targetTypes: "Target types",
    nameRequired: "Name required",
    policyUpdated: "Policy updated",
    policyCreated: "Policy created",
    policyDeleted: "Policy deleted",
    // job history
    jobHistorySubtitle: "Recent backup job executions — {total} total jobs",
    allStatuses: "All statuses",
    searchJobs: "Search jobs...",
    jobName: "Job Name",
    started: "Started",
    duration: "Duration",
    size: "Size",
    result: "Result",
    noJobHistory: "No job history found",
    deleted: "Deleted",
    deleteFailed: "Delete failed",
    // schedules
    newSchedule: "New Schedule",
    automatedSchedulesCount: "Automated backup schedules — {total} configured",
    noSchedulesYet: "No schedules yet. Create one to automate backups.",
    editSchedule: "Edit Schedule",
    scheduleName: "Schedule Name",
    frequency: "Frequency",
    cronExpressionCustom: "Cron Expression (custom)",
    backupJob: "Backup Job",
    notifyOn: "Notify on",
    descriptionOptional: "Description (optional)",
    currentSchedule: "Current schedule",
    scheduleUpdated: "Schedule updated",
    scheduleCreated: "Schedule created",
    scheduleDeleted: "Schedule deleted",
    failedToSave: "Failed to save",
    failedToDelete: "Failed to delete",
    allFieldsRequired: "All fields required",
    activeScheduleLabel: "Active",
    disabledScheduleLabel: "Disabled",
    // activity log
    activityLogTitle: "Activity Log",
    activityLogSubtitle: "System events and backup activity — {total} entries",
    allLevels: "All levels",
    searchLogs: "Search log messages...",
    noLogEntries: "No log entries found",
    // settings
    settingsTitle: "Settings",
    settingsSubtitle: "Application configuration and system tools",
    settingsGeneral: "General",
    settingsNotifications: "Notifications",
    settingsRetention: "Retention",
    settingsSystemTools: "System Tools",
    settingsAppearance: "Appearance",
    darkMode: "Dark Mode",
    darkModeDesc: "Toggle dark/light theme",
    scheduleDefaults: "Schedule Defaults",
    networkAccess: "Network Access",
    applicationUrl: "Application URL",
    applicationUrlDesc: "Leave empty to use the detected local IP. Set a custom URL if the server is behind DNS, VPN, or reverse proxy.",
    bindHost: "Bind Host",
    bindHostDesc: "Network interface used by the server. Use 0.0.0.0 to accept LAN connections. Restart the service after changing it.",
    detectedLocalIp: "Detected Local IP",
    currentAccessUrl: "Current Access URL",
    timezone: "Timezone",
    version: "Version",
    smtp: "SMTP (Email)",
    emailOnFailure: "Email on failure",
    emailOnFailureDesc: "Send email when backup fails",
    emailOnSuccess: "Email on success",
    emailOnSuccessDesc: "Send email when backup completes",
    slackWebhook: "Slack Webhook URL",
    slackDesc: "Create an Incoming Webhook in Slack Apps",
    discordWebhook: "Discord Webhook URL",
    discordDesc: "Create a Webhook in Discord channel settings",
    telegramBotToken: "Bot Token",
    telegramChatId: "Chat ID",
    telegramDesc: "Get token from @BotFather, chat ID from @userinfobot",
    genericWebhook: "Generic Webhook",
    genericWebhookDesc: "POST JSON payload to any HTTP endpoint",
    webhookUrl: "Webhook URL",
    enableRetentionPolicy: "Enable retention policy",
    enableRetentionPolicyDesc: "Automatically clean up old backups",
    keepBackupsForDays: "Keep backups for (days)",
    systemRequirements: "System Requirements",
    systemRequirementsDesc: "Check which CLI tools are available on this server. Required for database, VM, and cloud backups.",
    toolCol: "Tool",
    requiredForCol: "Required For",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved",
    installed: "Installed",
    notFoundStatus: "Not found",
    // users
    newUser: "New User",
    usersSubtitle: "Manage user accounts and role assignments",
    created: "Created",
    noUsers: "No users",
    userRequiredFields: "Username, password, and role required",
    userUpdated: "User updated",
    userCreated: "User created",
    userDeleted: "User deleted",
    leaveBlankToKeep: "Leave blank to keep current",
    // roles
    newRole: "New Role",
    rolesSubtitle: "Define user roles and their permissions",
    permissionsCol: "Permissions (enabled)",
    levelCol: "Level",
    noRoles: "No roles",
    roleName: "Role Name",
    roleUpdated: "Role updated",
    roleCreated: "Role created",
    roleDeleted: "Role \"{name}\" deleted",
    cannotDeleteBuiltIn: "Cannot delete built-in role",
    // permission labels
    perm_manageUsers: "Manage Users",
    perm_manageBackups: "Manage Backups",
    perm_manageSchedules: "Manage Schedules",
    perm_restore: "Restore Backups",
    perm_delete: "Delete Backups",
    perm_configure: "Configure Settings",
    perm_viewLogs: "View Logs",
    perm_manageRoles: "Manage Roles",
    // repos
    repositories: "Repositories",
    reposSubtitle: "Backup storage repositories",
    repoManagement: "Repository Management",
    comingSoonRepos: "Coming soon — configure backup destinations",
    // cron builder
    cronFrequencyType: "Frequency Type",
    cronHourly: "Hourly",
    cronDaily: "Daily",
    cronWeekly: "Weekly",
    cronMonthly: "Monthly",
    cronAdvanced: "Advanced (Cron Expression)",
    everyXHours: "Every X Hours",
    atMinute: "At Minute",
    dayOfWeek: "Day of Week",
    dayOfMonth: "Day of Month",
    runTime: "Run Time",
    // settings tabs & details
    settingsSecurity: "Security",
    settingsAdvanced: "Advanced",
    sessionTimeout: "Session Timeout (minutes)",
    preventConcurrent: "Prevent Concurrent Sessions",
    minPasswordLength: "Minimum Password Length",
    tempPath: "Custom Temporary Folder",
    bandwidthLimit: "Bandwidth Limit (MB/s, 0 for unlimited)",
    compressionLevel: "Compression Level",
    compressionNone: "None",
    compressionLow: "Low (Fastest)",
    compressionMedium: "Medium",
    compressionHigh: "High (Slowest)",
    limitStorageUsage: "Limit Storage Space (Quota)",
    limitStorageUsageDesc: "Limit storage used by this backup system manually instead of checking disk capacity",
    customStorageLimit: "Custom Storage Limit (GB)",
    storageQuotaLimit: "Quota Limit",
    storageRealDisk: "Physical Disk",
    disks: "Disks",
    settingsLdap: "LDAP / SSO",
    ldapEnabled: "Enable LDAP Authentication",
    ldapServerUrl: "LDAP Server URL",
    ldapBaseDn: "Base DN",
    ldapBindDn: "Bind DN",
    ldapBindPassword: "Bind Password",
    ldapUserFilter: "User Search Filter",
    ldapGroupMapping: "Group Role Mapping (JSON)",
  },
  uk: {
    // common
    appName: "Система резервного копіювання BCK",
    allSystemsOperational: "Усі системи працюють стабільно",
    healthy: "Стабільно",
    degraded: "Погіршено",
    idle: "Очікування",
    refresh: "Оновити",
    download: "Завантажити",
    viewAll: "Переглянути все",
    actions: "Дії",
    edit: "Редагувати",
    delete: "Видалити",
    save: "Зберегти",
    cancel: "Скасувати",
    create: "Створити",
    add: "Додати",
    name: "Назва",
    status: "Статус",
    createdAt: "Створено",
    updatedAt: "Оновлено",
    loading: "Завантаження...",
    error: "Помилка",
    success: "Успішно",
    info: "Інфо",
    warning: "Попередження",
    search: "Пошук",
    type: "Тип",
    active: "Активний",
    inactive: "Неактивний",
    yes: "Так",
    no: "Ні",
    confirm: "Підтвердити",
    description: "Опис",
    role: "Роль",
    email: "Електронна пошта",
    username: "Ім'я користувача",
    password: "Пароль",
    // sidebar & navbar
    dashboard: "Дашборд",
    backups: "Резервні копії",
    allBackups: "Усі завдання",
    databases: "Бази даних",
    vms: "Віртуальні машини",
    hosts: "Хости",
    cloud: "Хмари",
    restore: "Відновлення",
    policies: "Політики очищення",
    history: "Історія завдань",
    logs: "Журнал подій",
    settings: "Налаштування",
    users: "Користувачі",
    roles: "Ролі",
    logout: "Вийти",
    // login
    loginTitle: "Авторизація",
    loginSubtitle: "BCK Консоль керування копіями",
    loginButton: "Увійти",
    loginError: "Неправильні облікові дані або акаунт вимкнено",
    defaultCredentials: "Облікові дані за замовчуванням",
    // dashboard
    sysOverview: "Огляд системи",
    sources: "Джерела даних",
    last24h: "За останні 24 години",
    performance: "Швидкість та терміни",
    storage: "Обсяг сховища",
    dailyBackupSize: "Щоденний обсяг копій",
    recentActivity: "Остання активність",
    backupTimeline: "Графік копіювання",
    recentBackups: "Останні резервні копії",
    quickActions: "Швидкі дії",
    activeSchedules: "Активні розклади",
    totalJobs: "Всього завдань",
    completed: "Успішно",
    failed: "Помилка",
    running: "Виконується",
    activeNow: "Активні / Очікують",
    avgSpeed: "МБ/с середнє",
    expiringSoon: "застарівають >{days}д",
    used: "використано",
    ofTotal: "з {total} ГБ доступно",
    noDataYet: "Немає даних",
    noRecentActivity: "Подій не зафіксовано",
    noBackupsYet: "Немає створених копій",
    noActiveSchedules: "Немає активних розкладів. Створіть розклад для автоматизації копіювання.",
    createFirstBackup: "Створіть першу копію",
    newBackupBtn: "Нова копія",
    manageSchedulesBtn: "Керувати розкладами",
    exportDashboardBtn: "Експортувати дашборд",
    retentionInfo: "Політика: {days} днів · {total} копій всього · {expiring} застарівають",
    lastUpdated: "Останнє оновлення",
    // backups CRUD
    addBackup: "Додати завдання",
    editBackup: "Редагувати завдання",
    sourcePath: "Шлях до джерела",
    destPath: "Шлях збереження",
    backupType: "Тип резервної копії",
    runNow: "Запустити",
    noBackupsConfigured: "Немає налаштованих завдань",
    deleteConfirmTitle: "Видалити завдання?",
    deleteConfirmDesc: "Ви впевнені, що хочете видалити це завдання? Цю дію неможливо скасувати.",
    // db connections
    dbConnections: "Підключення до БД",
    addConnection: "Додати підключення",
    editConnection: "Редагувати підключення",
    testConnection: "Тестувати підключення",
    port: "Порт",
    databaseName: "Назва бази даних",
    databasesFound: "Знайдено баз даних",
    connectionSuccess: "Підключення успішне",
    connectionFailed: "Помилка підключення",
    // vm backups
    vmName: "Назва ВМ",
    datastore: "Сховище даних",
    host: "Хост",
    // cloud credentials
    cloudCredentials: "Ключі хмарних сховищ",
    addCredentials: "Додати ключі",
    editCredentials: "Редагувати ключі",
    provider: "Провайдер",
    accessKeyId: "Access Key ID",
    secretAccessKey: "Secret Access Key",
    region: "Регіон",
    bucket: "Бакет",
    endpoint: "Ендпоінт (необов'язково)",
    storageAccount: "Обліковий запис Azure",
    container: "Контейнер",
    // restore
    restoreTitle: "Відновлення системи",
    restoreSubtitle: "Відновлення систем, баз даних або ВМ з точок копіювання",
    restorePoint: "Оберіть точку копіювання",
    targetConnection: "Цільове підключення",
    targetPath: "Шлях відновлення",
    restoreBtn: "Почати відновлення",
    restoreSuccess: "Відновлення завершено успішно",
    restoreFailed: "Помилка відновлення",
    // policies
    retentionPolicies: "Політики збереження",
    retentionDays: "Термін збереження (днів)",
    retentionCopies: "Макс. кількість копій",
    smtpConfig: "Налаштування SMTP",
    smtpHost: "Сервер SMTP",
    smtpPort: "Порт SMTP",
    encryption: "Шифрування",
    // schedules
    schedules: "Розклади",
    scheduleList: "Розклади копіювання",
    cronExpression: "Крон-вираз (Cron)",
    cronHelper: "Стандартний синтаксис cron (* * * * *)",
    everyHour: "Щогодини",
    dailyAtMidnight: "Щодня опівночі",
    weeklySunday: "Щотижня (у неділю)",
    monthlyFirst: "Щомісяця (1-го числа)",
    custom: "Користувацький",
    runsEveryHour: "Запускається щогодини",
    runsDailyAtMidnight: "Запускається щодня опівночі",
    runsWeeklyOnSunday: "Запускається щотижня у неділю",
    runsMonthlyOn1st: "Запускається щомісяця 1-го числа",
    customSchedule: "Користувацький розклад",
    nextRun: "Наступний запуск",
    // users
    userList: "Керування користувачами",
    addUser: "Додати користувача",
    editUser: "Редагувати користувача",
    // roles
    roleList: "Керування ролями",
    addRole: "Додати роль",
    editRole: "Редагувати роль",
    permissions: "Дозволи та права",
    // policies
    policiesTitle: "Політики резервного копіювання",
    policiesSubtitle: "Попередньо налаштовані політики резервного копіювання з правилами збереження та розкладами",
    newPolicy: "Нова політика",
    policyName: "Назва політики",
    policy: "Політика",
    retention: "Збереження",
    schedule: "Розклад",
    targets: "Цілі",
    enabledCol: "Увімкнено",
    apply: "Застосувати",
    policyApplied: "Політику \"{name}\" застосовано до відповідних завдань копіювання",
    editPolicy: "Редагувати політику",
    newPolicyTitle: "Нова політика резервного копіювання",
    minCopiesToKeep: "Мін. кількість копій",
    cronSchedule: "Розклад Cron",
    targetTypes: "Типи цілей",
    nameRequired: "Необхідно вказати назву",
    policyUpdated: "Політику оновлено",
    policyCreated: "Політику створено",
    policyDeleted: "Політику видалено",
    // job history
    jobHistorySubtitle: "Останні запуски завдань — всього {total}",
    allStatuses: "Всі статуси",
    searchJobs: "Шукати завдання...",
    jobName: "Назва завдання",
    started: "Запущено",
    duration: "Тривалість",
    size: "Розмір",
    result: "Результат",
    noJobHistory: "Історію завдань не знайдено",
    deleted: "Видалено",
    deleteFailed: "Помилка видалення",
    // schedules
    newSchedule: "Новий розклад",
    automatedSchedulesCount: "Автоматичні розклади копіювання — налаштовано {total}",
    noSchedulesYet: "Немає створених розкладів. Створіть новий для автоматизації копіювання.",
    editSchedule: "Редагувати розклад",
    scheduleName: "Назва розкладу",
    frequency: "Періодичність",
    cronExpressionCustom: "Вираз Cron (користувацький)",
    backupJob: "Завдання резервного копіювання",
    notifyOn: "Сповіщати при",
    descriptionOptional: "Опис (необов'язково)",
    currentSchedule: "Поточний розклад",
    scheduleUpdated: "Розклад оновлено",
    scheduleCreated: "Розклад створено",
    scheduleDeleted: "Розклад видалено",
    failedToSave: "Не вдалося зберегти",
    failedToDelete: "Не вдалося видалити",
    allFieldsRequired: "Заповніть усі поля",
    activeScheduleLabel: "Активний",
    disabledScheduleLabel: "Вимкнено",
    // activity log
    activityLogTitle: "Журнал подій",
    activityLogSubtitle: "Системні події та активність резервного копіювання — {total} записів",
    allLevels: "Всі рівні",
    searchLogs: "Шукати повідомлення журналу...",
    noLogEntries: "Немає записів у журналі",
    // settings
    settingsTitle: "Налаштування",
    settingsSubtitle: "Конфігурація додатка та системні утиліти",
    settingsGeneral: "Загальні",
    settingsNotifications: "Сповіщення",
    settingsRetention: "Очищення",
    settingsSystemTools: "Системний стан",
    settingsAppearance: "Зовнішній вигляд",
    darkMode: "Темна тема",
    darkModeDesc: "Перемикання темної/світлої теми",
    scheduleDefaults: "Параметри розкладу",
    networkAccess: "Доступ до сервера",
    applicationUrl: "URL додатка",
    applicationUrlDesc: "Залиште порожнім, щоб використовувати локальний IP автоматично. Вкажіть URL вручну, якщо сервер за DNS, VPN або reverse proxy.",
    bindHost: "Адреса прослуховування",
    bindHostDesc: "Мережевий інтерфейс сервера. 0.0.0.0 приймає підключення з LAN. Після зміни перезапустіть сервіс.",
    detectedLocalIp: "Визначений локальний IP",
    currentAccessUrl: "Поточний URL доступу",
    timezone: "Часовий пояс",
    version: "Версія",
    smtp: "SMTP (Електронна пошта)",
    emailOnFailure: "Пошта при збої",
    emailOnFailureDesc: "Надсилати листа у разі помилки копіювання",
    emailOnSuccess: "Пошта при успіху",
    emailOnSuccessDesc: "Надсилати листа у разі успішного копіювання",
    slackWebhook: "Slack Webhook URL",
    slackDesc: "Створіть Incoming Webhook у Slack Apps",
    discordWebhook: "Discord Webhook URL",
    discordDesc: "Створіть Webhook в налаштуваннях каналу Discord",
    telegramBotToken: "Токен бота Telegram",
    telegramChatId: "Chat ID Telegram",
    telegramDesc: "Отримайте токен у @BotFather, chat ID у @userinfobot",
    genericWebhook: "Користувацький Webhook",
    genericWebhookDesc: "Надсилання POST JSON на будь-який HTTP-ендпоінт",
    webhookUrl: "Webhook URL",
    enableRetentionPolicy: "Увімкнути політику очищення",
    enableRetentionPolicyDesc: "Автоматично видаляти застарілі резервні копії",
    keepBackupsForDays: "Зберігати копії (днів)",
    systemRequirements: "Системні вимоги",
    systemRequirementsDesc: "Перевірка наявності утиліт CLI на цьому сервері. Необхідно для копіювання баз даних, ВМ та хмарних сховищ.",
    toolCol: "Утиліта",
    requiredForCol: "Призначення",
    saveSettings: "Зберегти налаштування",
    settingsSaved: "Налаштування збережено",
    installed: "Встановлено",
    notFoundStatus: "Не знайдено",
    // users
    newUser: "Новий користувач",
    usersSubtitle: "Керування обліковими записами користувачів та призначенням ролей",
    created: "Створено",
    noUsers: "Немає користувачів",
    userRequiredFields: "Ім'я користувача, пароль та роль є обов'язковими",
    userUpdated: "Користувача оновлено",
    userCreated: "Користувача створено",
    userDeleted: "Користувача видалено",
    leaveBlankToKeep: "Залиште порожнім, щоб не змінювати",
    // roles
    newRole: "Нова роль",
    rolesSubtitle: "Створення та налаштування ролей користувачів та їх дозволів",
    permissionsCol: "Дозволи (увімкнено)",
    levelCol: "Рівень",
    noRoles: "Немає ролей",
    roleName: "Назва ролі",
    roleUpdated: "Роль оновлено",
    roleCreated: "Роль створено",
    roleDeleted: "Роль \"{name}\" видалено",
    cannotDeleteBuiltIn: "Неможливо видалити вбудовану роль",
    // permission labels
    perm_manageUsers: "Керування користувачами",
    perm_manageBackups: "Керування резервними копіями",
    perm_manageSchedules: "Керування розкладами",
    perm_restore: "Відновлення з копій",
    perm_delete: "Видалення резервних копій",
    perm_configure: "Зміна налаштувань",
    perm_viewLogs: "Перегляд журналів",
    perm_manageRoles: "Керування ролями",
    // repos
    repositories: "Репозиторії",
    reposSubtitle: "Сховища для зберігання резервних копій",
    repoManagement: "Керування репозиторіями",
    comingSoonRepos: "Незабаром — налаштування місць призначення копій",
    // cron builder
    cronFrequencyType: "Тип розкладу",
    cronHourly: "Щогодини",
    cronDaily: "Щодня",
    cronWeekly: "Щотижня",
    cronMonthly: "Щомісяця",
    cronAdvanced: "Додатково (Крон-вираз)",
    everyXHours: "Кожні X годин",
    atMinute: "На хвилині",
    dayOfWeek: "День тижня",
    dayOfMonth: "День місяця",
    runTime: "Час запуску",
    // settings tabs & details
    settingsSecurity: "Безпека",
    settingsAdvanced: "Додатково",
    sessionTimeout: "Таймаут сесії (хвилин)",
    preventConcurrent: "Заборонити одночасні сесії",
    minPasswordLength: "Мінімальна довжина пароля",
    tempPath: "Користувацька тимчасова папка",
    bandwidthLimit: "Обмеження пропускної здатності (МБ/с, 0 - без обмежень)",
    compressionLevel: "Рівень стиснення",
    compressionNone: "Немає",
    compressionLow: "Низький (найшвидше)",
    compressionMedium: "Середній",
    compressionHigh: "Високий (найповільніше)",
    limitStorageUsage: "Обмежити обсяг сховища (квота)",
    limitStorageUsageDesc: "Встановити ліміт обсягу копій вручну замість перевірки ємності всього диска",
    customStorageLimit: "Користувацька квота сховища (ГБ)",
    storageQuotaLimit: "Обмеження квоти",
    storageRealDisk: "Фізичний диск",
    disks: "Диски",
    settingsLdap: "LDAP / SSO",
    ldapEnabled: "Увімкнути LDAP авторизацію",
    ldapServerUrl: "URL сервера LDAP",
    ldapBaseDn: "Base DN",
    ldapBindDn: "Bind DN",
    ldapBindPassword: "Пароль зв'язку (Bind Password)",
    ldapUserFilter: "Фільтр пошуку користувачів",
    ldapGroupMapping: "Мапінг груп ролей (JSON)",
  }
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('bck-lang');
    if (saved === 'uk' || saved === 'en') return saved;
    // Auto-detect browser language
    const navLang = navigator.language || navigator.userLanguage;
    return (navLang && navLang.startsWith('uk')) ? 'uk' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('bck-lang', lang);
  }, [lang]);

  const t = useCallback((key, params = {}) => {
    let text = translations[lang]?.[key] || translations['en']?.[key] || key;
    // Replace parameters e.g. {days}
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });
    return text;
  }, [lang]);

  const value = useMemo(() => ({
    lang,
    setLang,
    t,
    isUk: lang === 'uk',
  }), [lang, t]);

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useTranslation() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useTranslation must be used inside LangProvider');
  return ctx;
}
