export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    me: '/auth/me',
  },
  cloud: {
    base: '/cloud/accounts',
    list: () => '/cloud/accounts',
    get: (id: string) => `/cloud/accounts/${id}`,
    register: () => '/cloud/accounts',
    remove: (id: string) => `/cloud/accounts/${id}`,
    restorable: (id: string) => `/cloud/accounts/${id}/restorable`,
    restore: (id: string) => `/cloud/accounts/${id}/restore`,
    accountRestores: (id: string) => `/cloud/accounts/${id}/restores`,
    allRestores: () => '/cloud/restores',
    restoreById: (rid: string) => `/cloud/restores/${rid}`,
  },
  jobs: {
    list: () => '/jobs',
    get: (id: string) => `/jobs/${id}`,
    create: () => '/jobs',
    update: (id: string) => `/jobs/${id}`,
    remove: (id: string) => `/jobs/${id}`,
    run: (id: string) => `/jobs/${id}/run`,
    cancel: (id: string) => `/jobs/${id}/cancel`,
  },
  repositories: {
    list: () => '/repositories',
    create: () => '/repositories',
    remove: (id: string) => `/repositories/${id}`,
  },
  snapshots: {
    list: (params?: { job_id?: string; limit?: number }) => '/snapshots',
    remove: (id: string) => `/snapshots/${id}`,
  },
  restore: {
    file: () => '/restore/file',
    explore: (snapshotId: string) => `/restore/explore/${snapshotId}`,
    session: (id: string) => `/restore/session/${id}`,
    instant: {
      list: () => '/restore/instant',
      vm: () => '/restore/instant/vm',
      stop: (id: string) => `/restore/instant/${id}/stop`,
    },
  },
  agents: {
    list: () => '/agents',
    remove: (id: string) => `/agents/${id}`,
  },
  events: {
    list: (limit = 50) => `/events?limit=${limit}`,
  },
  dashboard: {
    stats: () => '/dashboard/stats',
  },
  hypervisors: {
    list: () => '/hypervisors',
    vms: (id: string) => `/hypervisors/${id}/vms`,
    backupVm: (id: string, vmRef: string) => `/hypervisors/${id}/vms/${vmRef}/backup`,
  },
  portal: {
    me: () => '/portal/me',
    myRequests: () => '/portal/restore-requests',
    submit: () => '/portal/restore-requests',
    cancel: (id: string) => `/portal/restore-requests/${id}/cancel`,
    allRequests: () => '/portal/admin/restore-requests',
    approve: (id: string) => `/portal/admin/restore-requests/${id}/approve`,
    reject: (id: string) => `/portal/admin/restore-requests/${id}/reject`,
    complete: (id: string) => `/portal/admin/restore-requests/${id}/complete`,
  },
  sobr: {
    tiers: () => '/sobr',
    addTier: () => '/sobr/tiers',
    policies: () => '/sobr/policies',
    createPolicy: () => '/sobr/policies',
    execute: (id: string) => `/sobr/policies/${id}/execute`,
  },
  m365: {
    tenants: () => '/m365/tenants',
    registerTenant: () => '/m365/tenants',
    jobs: () => '/m365/jobs',
    startBackup: () => '/m365/jobs',
  },
  tape: {
    drives: () => '/tape/drives',
    registerDrive: () => '/tape/drives',
    media: () => '/tape/media',
    addMedia: () => '/tape/media',
    formatMedia: () => '/tape/media/format',
    loadMedia: (driveId: string) => `/tape/drives/${driveId}/load`,
    ejectMedia: (driveId: string) => `/tape/drives/${driveId}/eject`,
    write: (driveId: string) => `/tape/drives/${driveId}/write`,
    read: (driveId: string) => `/tape/drives/${driveId}/read`,
    applyRetention: () => '/tape/retention',
  },
  cdp: {
    policies: () => '/cdp/policies',
    createPolicy: () => '/cdp/policies',
    start: (id: string) => `/cdp/policies/${id}/start`,
    sessions: () => '/cdp/sessions',
    stop: (id: string) => `/cdp/sessions/${id}/stop`,
    stats: () => '/cdp/stats',
  },
  dr: {
    status: () => '/dr/status',
    sites: () => '/dr/sites',
    registerSite: () => '/dr/sites',
    plans: () => '/dr/plans',
    createPlan: () => '/dr/plans',
    failover: (id: string) => `/dr/plans/${id}/failover`,
    failback: (id: string) => `/dr/plans/${id}/failback`,
    test: (id: string) => `/dr/plans/${id}/test`,
  },
  sso: {
    providers: () => '/auth/sso/providers',
    registerProvider: () => '/auth/sso/providers',
    addLdap: () => '/auth/sso/ldap',
  },
  tenants: {
    list: () => '/tenants',
    get: (id: string) => `/tenants/${id}`,
    create: () => '/tenants',
    remove: (id: string) => `/tenants/${id}`,
    suspend: (id: string) => `/tenants/${id}/suspend`,
    activate: (id: string) => `/tenants/${id}/activate`,
    disable: (id: string) => `/tenants/${id}/disable`,
    updateQuota: (id: string) => `/tenants/${id}/quota`,
    updateSettings: (id: string) => `/tenants/${id}/settings`,
  },
} as const;

export type ApiRoutes = typeof API_ROUTES;